=== kaisarepraneet/Webstack/Tiffin-System/EMSSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="Company">
		<xsd:complexType>
            <xsd:sequence>		
            <xsd:element name="Employee">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="EmpName" type="xs:string"/>
                        <xsd:element name="EmpAge" type="xs:integer"/>
                        <xsd:element name="EmpSalary">
                            <xs:simpletype>
                                <xs:restriction base:"xs:double">
                                    <xs:minInclusive value="50000"/>
                                    <xs:maxInclusive value="200000"/>
                                </xs:restriction>
                            </xs:simpletype>
                        </xs:element>
                        <xsd:element name="EmpEmailId" type="xs:string"/>
                        <xsd:element name="EmpPhonenum" type="xs:string"/>
                        <xsd:element name="EmpDesignation" type="xs:string"/>					
                    </xsd:sequence>	
                </xsd:complexType>
            </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
	</xsd:element>
</xsd:schema>

=== kaisarepraneet/Webstack/Exam/EMS.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="EMSStyle.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EMSSchema.xsd">
    <Employee>
        <EmpName>Praneet Kaisare</EmpName>
        <EmpAge>20</EmpAge>
        <EmpSalary>50000</EmpSalary>
        <EmpEmailId>praneet@gmail.com</EmpEmailId>
        <EmpPhonenum>+91-9427638635</EmpPhonenum>
        <EmpDesignation>Manager</EmpDesignation>
    </Employee>
    <Employee>
        <EmpName>Yash Kataria</EmpName>
        <EmpAge>22</EmpAge>
        <EmpSalary>45000</EmpSalary>
        <EmpEmailId>yash@gmail.com</EmpEmailId>
        <EmpPhonenum>+91-9876543210</EmpPhonenum>
        <EmpDesignation>Ass. Manager</EmpDesignation>
    </Employee>
    <Employee>
        <EmpName>Kishan Mistry</EmpName>
        <EmpAge>30</EmpAge>
        <EmpSalary>60000</EmpSalary>
        <EmpEmailId>kishan@gmail.com</EmpEmailId>
        <EmpPhonenum>+91-9876453201</EmpPhonenum>
        <EmpDesignation>HR Head</EmpDesignation>
    </Employee>
</Company>
