=== kaisarepraneet/Webstack/Tiffin-System/Lab Test 2/StudentsSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="Students">
	<xsd:complexType>
		<xsd:element name="Student">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:element name="Name" type="xs:string"/>
					<xsd:element name="Age" type="xs:integer"/>
					<xsd:element name="College" type="xs:string"/>
				</xsd:sequence>	
			</xsd:complexType>
		</xsd:element>

	</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== kaisarepraneet/Webstack/Tiffin-System/Lab Test 2/Student.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="StudentsSchema.xsd">

<Student>
    <Name>Praneet</Name>
    <Age>21</Age>
    <College>Christ University</College>
</Student>
<Student>
    <Name>Yash</Name>
    <Age>21</Age>
    <College>St. Joseph University</College>
</Student>
<Student>
    <Name>Kishan</Name>
    <Age>21</Age>
    <College>Christ University</College>
</Student>
